// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ruuvi.Data;

namespace Ruuvi.Migrations
{
    [DbContext(typeof(RuuviDbContext))]
    [Migration("20200924101103_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ruuvi.Models.Tag", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AccelX")
                        .HasColumnType("double");

                    b.Property<double>("AccelY")
                        .HasColumnType("double");

                    b.Property<double>("AccelZ")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DataFormat")
                        .HasColumnType("int");

                    b.Property<int>("DefaultBackground")
                        .HasColumnType("int");

                    b.Property<bool>("Favorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Humidity")
                        .HasColumnType("double");

                    b.Property<double>("HumidityOffset")
                        .HasColumnType("double");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int>("MeasurementSequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("MovementCounter")
                        .HasColumnType("int");

                    b.Property<long>("Pressure")
                        .HasColumnType("bigint");

                    b.Property<int>("Rssi")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Voltage")
                        .HasColumnType("double");

                    b.Property<int>("txPower")
                        .HasColumnType("int");

                    b.HasKey("IdTag");

                    b.ToTable("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
